import 'package:haron_pos/data/model/product.dart';
import 'package:hive/hive.dart';

part 'order.g.dart'; // This file will be generated by the build runner

@HiveType(typeId: 1)
class Order {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final List<Product> products; // Assuming you have a Product class
  @HiveField(2)
  final double totalAmount;
  @HiveField(3)
  final DateTime date;

  Order({
    required this.id,
    required this.products,
    required this.totalAmount,
    required this.date,
  });
}
